services:
  - type: web
    name: ulla-valentine
    env: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install && cp -r ../build ./build
    startCommand: cd server && node index.js
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false
      - key: NODE_ENV
        value: production
