services:
  - type: web
    name: ulla-valentine
    env: node
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false
      - key: NODE_ENV
        value: production
